version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=457738878798.dkr.ecr.eu-west-3.amazonaws.com/nginx
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG="latest"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 457738878798.dkr.ecr.eu-west-3.amazonaws.com/nginx:latest .
      - docker tag 457738878798.dkr.ecr.eu-west-3.amazonaws.com/nginx $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push 457738878798.dkr.ecr.eu-west-3.amazonaws.com/nginx:latest
artifacts:
  files:
    - imageDetail.json

